; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
monitor_speed = 115200
build_flags = -DMQTT_MAX_PACKET_SIZE=512
lib_deps = 
	knolleary/PubSubClient@^2.8
	esphome/AsyncTCP-esphome@^1.2.2
	ottowinter/ESPAsyncWebServer-esphome@^2.1.0
	milesburton/DallasTemperature@^3.10.0

[env:production]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = ${common.monitor_speed}
build_flags = 
	${common.build_flags}
	-DMQTT_CLIENT_ID=\"PoolMonitor\"
	-DMQTT_TOPIC=\"pool/monitor\"
lib_deps = ${common.lib_deps}
upload_protocol = espota
upload_port = 192.168.0.163

[env:test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = ${common.monitor_speed}
build_flags = 
	${common.build_flags}
	-DMQTT_CLIENT_ID=\"PoolMonitor_Test\"
	-DMQTT_TOPIC=\"pool/monitor/test\"
lib_deps = ${common.lib_deps}
upload_protocol = espota
upload_port = 192.168.0.167
